### ISSUE TITLE
[FEATURE] 카카오 소셜 로그인

### ISSUE THREAD

**Issue by nayeongdev** [HotCake-Tanghuru/HotCake-BE#10]
**Feature 요청에 대한 설명**
카카오 소셜 로그인은 사용자가 카카오 계정을 사용하여 애플리케이션에 로그인할 수 있는 기능입니다.
사용자는 카카오 계정으로 간편하게 로그인하여 애플리케이션에 접근할 수 있으며, 별도의 회원가입 절차 없이도 서비스를 이용할 수 있습니다.

**해결하고자 하는 문제(Why)**
1. 편의성: 소셜 로그인은 사용자에게 로그인 절차를 단순화하여 편의성을 제공합니다. 사용자는 기존에 가입한 소셜 계정을 활용하여 간편하게 로그인할 수 있으며, 별도의 아이디와 비밀번호를 기억하거나 입력할 필요가 없습니다.
2. 시간 절약: 소셜 로그인은 사용자가 회원가입 절차를 거치지 않고도 서비스를 이용할 수 있도록 합니다. 사용자는 소셜 계정의 인증을 통해 신속하게 로그인하여 서비스를 이용할 수 있습니다.
3. 신뢰성: 소셜 로그인은 소셜 플랫폼에서 제공하는 인증 시스템을 활용하기 때문에 보안성이 높습니다. 사용자의 신원이 소셜 플랫폼을 통해 확인되므로, 가입한 서비스에서의 신원 인증에 대한 우려를 줄일 수 있습니다.

**원하는 솔루션 설명(How)**
사용자가 카카오 계정으로 로그인하면, 카카오 API를 통해 사용자 정보를 가져와서 애플리케이션 내에서 활용하는 것을 원합니다.

**TO-DO**
- [x] 카카오 개발자 사이트에서 애플리케이션 등록 진행
- [x] 애플리케이션 설정에서 카카오 소셜 로그인을 활성화하고, 필요한 권한과 동의 항목 설정
- [x] 애플리케이션 코드에 카카오 로그인 API를 통합하여 로그인 기능 구현

**기타**
![image](https://github.com/HotCake-Tanghuru/HotCake-BE/assets/108624466/0df7dded-5ad4-4aaf-9ea5-ff1acd0b6743)

![image](https://github.com/HotCake-Tanghuru/HotCake-BE/assets/108624466/ecd019f9-8d02-4493-b08e-25fc05144279)
