### ISSUE TITLE
[FEATURE] 유저 미션 리스트 조회 API

### ISSUE THREAD

**Issue by Ko-udon** [HotCake-Tanghuru/HotCake-BE#17]
**Feature 요청에 대한 설명**
유저의 참여한 트렌드 미션 목록들을 모두 볼 수 있는 기능을 제공합니다.

**해결하고자 하는 문제(Why)**
프로필에서 해당 유저가 참여중인 트렌드 미션 목록을 조회하여 특정 트렌드 미션 페이지를 보거나 참여중인 목록이 무엇인지 조회할 수 있습니다.

**원하는 솔루션 설명(How)**
  1. 해당 유저가 참여중인 트렌드 미션 목록을 제공합니다.
  2. 트렌드 미션안에 트렌드 아이템들은 반환하지 않습니다. (특정 트렌드 미션 페이지 조회시 반환하도록)
  3. 참여중인 트렌드 미션 목록이 없다면 에러가 아닌, 빈 배열을 반환합니다.

**TO-DO**
- [x] 유저 아이디값을 통해 참여중인 트렌드 미션 목록을 모두 조회
- [x] 트렌드 미션 목록을 JSON형태로 반환
- [x] 참여중인 트렌드 미션 목록이 없다면 빈 값을 반환

**기타**
![image](https://github.com/HotCake-Tanghuru/HotCake-BE/assets/79897135/3a1b0a42-0fd5-4b6f-91fe-a0f0aa841775)
