### ISSUE TITLE
[FEATURE] 트렌드 미션 상세조회 API

### ISSUE THREAD

**Issue by Ko-udon** [HotCake-Tanghuru/HotCake-BE#18]
**Feature 요청에 대한 설명**
해당하는 트렌드 미션에 대한 정보 조회

**해결하고자 하는 문제(Why)**
트렌드 미션 리스트에서 하나를 특정해서 정보를 조회하는데 필요합니다.

**원하는 솔루션 설명(How)**
상세 조회시, 트렌드 미션에 대한 정보와 연관된 사용자의 트렌드 아이템들도 모두 반환해야 합니다.
또한 해당 페이지(트렌드 미션)에 대한 댓글과 대댓글, 좋아요 값을 모두 반환해야 합니다.

**TO-DO**
- [x] url에 pk값을 담아 Get 요청을 통해 데이터 조회
- [x] 요청시, 트렌드 미션에 대한 정보와 연관된 사용자의 트렌드 아이템들도 모두 반환
- [ ] 댓글 정보 반환
- [ ] 좋아요 값 반환

**기타**
