### ISSUE TITLE
[FEATURE] 스탬프 발급 요청 API

### ISSUE THREAD

**Issue by Ko-udon** [HotCake-Tanghuru/HotCake-BE#22]
**Feature 요청에 대한 설명**
해당 트렌드 미션의 모든 아이템을 인증 후, 완료 요청 (체크)

**해결하고자 하는 문제(Why)**
미션 완수 후, 트렌드 미션의 상태값 변경 (완료)

**원하는 솔루션 설명(How)**
해당 트렌드 미션의 소유자만 요청 가능 (프론트에서 처리)

API 호출 시 해당 트렌드 미션이 존재하는지 여부 확인 후,
트렌드 미션의 아이템 항목들을 모두 인증 하였는지 확인,
미션 완료 상태값 변경

**TO-DO**
- [x] 요청값과 같은 트렌드 미션이 존재하지는지 확인
- [x] 해당 미션의 아이템 항목들 인증 여부 체크
- [x] 모두 인증 완료상태라면, 미션도 완료 상태로 변경

**기타**
기능 요청에 대한 추가적인 정보나 스크린샷 등이 있다면 여기에 추가해주세요.
