### ISSUE TITLE
[FEATURE] 유저의 스탬프 목록 조회 API

### ISSUE THREAD

**Issue by Ko-udon** [HotCake-Tanghuru/HotCake-BE#27]
**Feature 요청에 대한 설명**
사용자의 스탬프 목록 조회

**해결하고자 하는 문제(Why)**
프로필에서 스탬프 구경하기 -> 스탬프 목록을 화면에 보여줘야 함

**원하는 솔루션 설명(How)**
사용자의 id값을 url에 담아서 Get 요청으로 목록 조회

**TO-DO**
- [x] 없는 사용자의 경우 에러
- [x] 스탬프 목록은 없을 수도 있으므로 에러로 처리하지 않음
- [x] 해당 사용자의 스탬프 목록 반환

**기타**
