### ISSUE TITLE
[FEATURE] Swagger 적용

### ISSUE THREAD

**Issue by Ko-udon** [HotCake-Tanghuru/HotCake-BE#48]
**원하는 솔루션 설명(How)**
테스트하기 쉽도록 Swagger를 앱에 적용시켜 API 문서화를 통해 보다 명확하고, 이해하기 쉽게 합니다

**TO-DO**
- [x] accounts 앱 swagger 적용
- [x] trend 앱 swagger 적용
- [x] trend mission 앱 swagger 적용

**기타**
